version: "3.8"

services:
  database:
    container_name: "northwind_postgres"
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ./.env
    ports:
      - "4000:5432"
    volumes:
      # Mount your local "backup" folder to the PostgreSQL init directory
      - ./backup:/docker-entrypoint-initdb.d
      # Persist database data between container restarts
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
